spring:
  config:
    import:
      - postgresql-dev.yml
      - mongo-dev.yml

# Development Discord Webhook Configuration
notification:
  discord:
    user-registration:
      enabled: false
      webhook-url: ""
